# Generated by Django 4.1.4 on 2022-12-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter category name', max_length=200, verbose_name='Category Name')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categories ',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book name', max_length=200, verbose_name='Book Name')),
                ('image', models.ImageField(help_text='Upload book image', upload_to='book-images', verbose_name='Book Image')),
                ('author', models.CharField(help_text='Enter book author', max_length=150, verbose_name='Book Author')),
                ('about', models.TextField(help_text='Upload book description', verbose_name='Book Description')),
                ('file', models.FileField(help_text='Upload book file', upload_to='book-files', verbose_name='Book File')),
                ('book_pages', models.CharField(help_text='Enter book pages', max_length=150, verbose_name='Book Pages')),
                ('viewed', models.IntegerField(default=1)),
                ('downloaded', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(help_text='Choose categoy(ies)', to='books.category', verbose_name='Choose Category(ies)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Books ',
                'db_table': 'Books',
            },
        ),
    ]
