# Generated by Django 4.1.4 on 2022-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Books '},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories '},
        ),
        migrations.AddField(
            model_name='book',
            name='about_en',
            field=models.TextField(help_text='Upload book description', null=True, verbose_name='Book Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='about_ru',
            field=models.TextField(help_text='Upload book description', null=True, verbose_name='Book Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_en',
            field=models.CharField(help_text='Enter book name', max_length=200, null=True, verbose_name='Book Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='name_ru',
            field=models.CharField(help_text='Enter book name', max_length=200, null=True, verbose_name='Book Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Enter category name', max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Enter category name', max_length=200, null=True, verbose_name='Category Name'),
        ),
    ]
