# Generated by Django 4.1.4 on 2022-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_en',
            field=models.FileField(help_text='Upload book file', null=True, upload_to='book-files', verbose_name='Book File'),
        ),
        migrations.AddField(
            model_name='book',
            name='file_ru',
            field=models.FileField(help_text='Upload book file', null=True, upload_to='book-files', verbose_name='Book File'),
        ),
    ]
