# Generated by Django 4.1.4 on 2022-12-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_file_en_book_file_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Choose categoy(ies)', related_name='books', to='books.category', verbose_name='Choose Category(ies)'),
        ),
    ]
