# Generated by Django 4.1.4 on 2022-12-24 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
