# Generated by Django 4.1.4 on 2022-12-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comments_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
