# Generated by Django 4.1.4 on 2022-12-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_comments_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
